Models/Connection/DBConnection.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace shad_web_app.Models.Connection
{
    public class DBConnection
    {

        public static SqlConnection getConnection()
        {
            return new SqlConnection(@"Data Source=LAHIRUPC\SQLEXPRESS;Initial Catalog=test1;Integrated Security=True");
        }

    }
}

Models/DAO/UserDAO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using shad_web_app.Models.Entity;

namespace shad_web_app.Models.DAO
{
    interface UserDAO
    {

        string validate(string name, string password);

        string createUser(User user);

        List<User> getAllUsers();

        string updateUser(string name, string newPassword);

        string deleteUser(string name);

    }
}

Models/Entity/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace shad_web_app.Models.Entity
{
    public class User
    {

        private string userName;

        private string userPassword;

        private int userAge;

        private string userAddress;

        public User(string userName, string userPassword, int userAge, string userAddress)
        {
            this.userName = userName;
            this.userPassword = userPassword;
            this.userAge = userAge;
            this.userAddress = userAddress;
        }

        public User()
        {
        }

        public string UserName { get => userName; set => userName = value; }
        public string UserPassword { get => userPassword; set => userPassword = value; }
        public int UserAge { get => userAge; set => userAge = value; }
        public string UserAddress { get => userAddress; set => userAddress = value; }
    }
}

Models/Service/UserService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using shad_web_app.Models.DAO;
using shad_web_app.Models.Entity;
using shad_web_app.Models.Connection;
using System.Data.SqlClient;

namespace shad_web_app.Models.Service
{
    public class UserService : UserDAO
    {

        SqlConnection con = DBConnection.getConnection();

        public string createUser(User user)
        {
            try
            {
                SqlCommand cm = new SqlCommand("INSERT INTO UserTable (Uname, Upassword, Uage, Uaddress) VALUES ('" + user.UserName + "', '" + user.UserPassword + "', " + user.UserAge + ", '" + user.UserAddress + "');", con);

                con.Open();
                int i = cm.ExecuteNonQuery();

                if (i > 0)
                {
                    return "ok";
                }
                else
                {
                    return "not";
                }

            }
            catch (Exception e)
            {
                return e.Message;
            }
            finally
            {
                con.Close();
            }
        }

        public List<User> getAllUsers()
        {
            List<User> userList = new List<User>();

            try
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM UserTable", con);

                con.Open();

                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    userList.Add(new User(dr["Uname"].ToString(), dr["Upassword"].ToString(), int.Parse(dr["Uage"].ToString()), dr["Uaddress"].ToString()));
                }

                return userList;

            }
            catch (Exception e)
            {
                return null;
            }
            finally
            {
                con.Close();
            }
        }

        public string updateUser(string name, string newPassword)
        {
            throw new NotImplementedException();
        }

        public string validate(string name, string password)
        {
            try
            {
                string getName = null;
                string getPass = null;

                SqlCommand cmd = new SqlCommand("SELECT Uname, Upassword FROM UserTable WHERE Uname='"+name+"' AND Upassword='"+password+"' ;",con);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();

                while (dr.Read())
                {
                    getName = dr["Uname"].ToString();
                    getPass = dr["Upassword"].ToString();
                }

                if (getName.Equals(name) && getPass.Equals(password))
                {
                    return "ok";
                }
                else
                {
                    return "not";
                }

            }
            catch (Exception e)
            {
                return "error";
            }
            finally
            {
                con.Close();
            }
        }

        public string deleteUser(string name)
        {
            try
            {

                SqlCommand cmd = new SqlCommand("DELETE FROM UserTable WHERE Uname='"+name+"' ;", con);
                con.Open();
                int i = cmd.ExecuteNonQuery();

                if (i>0)
                {
                    return "ok";
                }
                else
                {
                    return "not";
                }


            }
            catch (Exception e)
            {
                return "error";
            }
            finally
            {
                con.Close();
            }
        }
    }
}

Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shad_web_app.Models.Entity;
using shad_web_app.Models.Service;

namespace shad_web_app.Controllers
{
    public class ApiController : Controller
    {

        UserService us = new UserService();

        [HttpPost]
        public ActionResult reg(User user)
        {
            string message = us.createUser(user);
            ViewBag.adw = user.UserName;
            ViewBag.adw2 = message;
            return View("../Home/Register");
        }

        [HttpPost]
        public ActionResult auth(string uname, string upass)
        {
            if (uname.Equals("admin") && upass.Equals("123"))
            {
                ViewBag.users = us.getAllUsers();

                ViewBag.msg = uname;
                return View("../Home/Home");
            }
            else
            {
                string state = us.validate(uname, upass);

                if (state.Equals("ok"))
                {
                    ViewBag.msg = uname;
                    return View("../Home/Home");
                }
                else
                {
                    ViewBag.msg = state;
                    return View("../Home/login_view");
                }
                
            }
        }

        public ActionResult getAllUsers()
        {
            ViewBag.users = us.getAllUsers();
            return View("../Home/Home");
        }

        public ActionResult deleteUser(string name)
        {
            string state = us.deleteUser(name);
            ViewBag.users = us.getAllUsers();
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace shad_web_app.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult login_view()
        {

            return View();
        }

        public ActionResult reg_view()
        {
            ViewBag.adw = null;
            return View("Register");
        }

        public ActionResult resetpw()
        {
            return View("ResetPassword");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

<link href="~/Content/table/dataTables.bootstrap.css" rel="stylesheet" />
<link href="~/Content/table/jquery.dataTables.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/table/jquery.dataTables.js"></script>
<script src="~/Scripts/table/dataTables.bootstrap.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {
        $('#example').DataTable();
    });
</script>


<table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Age</th>
            <th>Start date</th>
            <th>Salary</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011/04/25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Garrett Winters</td>
            <td>Accountant</td>
            <td>Tokyo</td>
            <td>63</td>
            <td>2011/07/25</td>
            <td>$170,750</td>
        </tr>
        <tr>
            <td>Ashton Cox</td>
            <td>Junior Technical Author</td>
            <td>San Francisco</td>
            <td>66</td>
            <td>2009/01/12</td>
            <td>$86,000</td>
        </tr>
        <tr>
            <td>Cedric Kelly</td>
            <td>Senior Javascript Developer</td>
            <td>Edinburgh</td>
            <td>22</td>
            <td>2012/03/29</td>
            <td>$433,060</td>
        </tr>
        <tr>
            <td>Airi Satou</td>
            <td>Accountant</td>
            <td>Tokyo</td>
            <td>33</td>
            <td>2008/11/28</td>
            <td>$162,700</td>
        </tr>
        <tr>
            <td>Brielle Williamson</td>
            <td>Integration Specialist</td>
            <td>New York</td>
            <td>61</td>
            <td>2012/12/02</td>
            <td>$372,000</td>
        </tr>
        <tr>
            <td>Herrod Chandler</td>
            <td>Sales Assistant</td>
            <td>San Francisco</td>
            <td>59</td>
            <td>2012/08/06</td>
            <td>$137,500</td>
        </tr>
        <tr>
            <td>Rhona Davidson</td>
            <td>Integration Specialist</td>
            <td>Tokyo</td>
            <td>55</td>
            <td>2010/10/14</td>
            <td>$327,900</td>
        </tr>
        <tr>
            <td>Colleen Hurst</td>
            <td>Javascript Developer</td>
            <td>San Francisco</td>
            <td>39</td>
            <td>2009/09/15</td>
            <td>$205,500</td>
        </tr>
        <tr>
            <td>Sonya Frost</td>
            <td>Software Engineer</td>
            <td>Edinburgh</td>
            <td>23</td>
            <td>2008/12/13</td>
            <td>$103,600</td>
        </tr>
        <tr>
            <td>Jena Gaines</td>
            <td>Office Manager</td>
            <td>London</td>
            <td>30</td>
            <td>2008/12/19</td>
            <td>$90,560</td>
        </tr>
        <tr>
            <td>Quinn Flynn</td>
            <td>Support Lead</td>
            <td>Edinburgh</td>
            <td>22</td>
            <td>2013/03/03</td>
            <td>$342,000</td>
        </tr>
        <tr>
            <td>Charde Marshall</td>
            <td>Regional Director</td>
            <td>San Francisco</td>
            <td>36</td>
            <td>2008/10/16</td>
            <td>$470,600</td>
        </tr>
        <tr>
            <td>Haley Kennedy</td>
            <td>Senior Marketing Designer</td>
            <td>London</td>
            <td>43</td>
            <td>2012/12/18</td>
            <td>$313,500</td>
        </tr>
        <tr>
            <td>Tatyana Fitzpatrick</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>19</td>
            <td>2010/03/17</td>
            <td>$385,750</td>
        </tr>
        <tr>
            <td>Michael Silva</td>
            <td>Marketing Designer</td>
            <td>London</td>
            <td>66</td>
            <td>2012/11/27</td>
            <td>$198,500</td>
        </tr>
        <tr>
            <td>Paul Byrd</td>
            <td>Chief Financial Officer (CFO)</td>
            <td>New York</td>
            <td>64</td>
            <td>2010/06/09</td>
            <td>$725,000</td>
        </tr>
        <tr>
            <td>Gloria Little</td>
            <td>Systems Administrator</td>
            <td>New York</td>
            <td>59</td>
            <td>2009/04/10</td>
            <td>$237,500</td>
        </tr>
        <tr>
            <td>Bradley Greer</td>
            <td>Software Engineer</td>
            <td>London</td>
            <td>41</td>
            <td>2012/10/13</td>
            <td>$132,000</td>
        </tr>
        <tr>
            <td>Dai Rios</td>
            <td>Personnel Lead</td>
            <td>Edinburgh</td>
            <td>35</td>
            <td>2012/09/26</td>
            <td>$217,500</td>
        </tr>
        <tr>
            <td>Jenette Caldwell</td>
            <td>Development Lead</td>
            <td>New York</td>
            <td>30</td>
            <td>2011/09/03</td>
            <td>$345,000</td>
        </tr>
        <tr>
            <td>Yuri Berry</td>
            <td>Chief Marketing Officer (CMO)</td>
            <td>New York</td>
            <td>40</td>
            <td>2009/06/25</td>
            <td>$675,000</td>
        </tr>
        <tr>
            <td>Caesar Vance</td>
            <td>Pre-Sales Support</td>
            <td>New York</td>
            <td>21</td>
            <td>2011/12/12</td>
            <td>$106,450</td>
        </tr>
        <tr>
            <td>Doris Wilder</td>
            <td>Sales Assistant</td>
            <td>Sydney</td>
            <td>23</td>
            <td>2010/09/20</td>
            <td>$85,600</td>
        </tr>
        <tr>
            <td>Angelica Ramos</td>
            <td>Chief Executive Officer (CEO)</td>
            <td>London</td>
            <td>47</td>
            <td>2009/10/09</td>
            <td>$1,200,000</td>
        </tr>
        <tr>
            <td>Gavin Joyce</td>
            <td>Developer</td>
            <td>Edinburgh</td>
            <td>42</td>
            <td>2010/12/22</td>
            <td>$92,575</td>
        </tr>
        <tr>
            <td>Jennifer Chang</td>
            <td>Regional Director</td>
            <td>Singapore</td>
            <td>28</td>
            <td>2010/11/14</td>
            <td>$357,650</td>
        </tr>
        <tr>
            <td>Brenden Wagner</td>
            <td>Software Engineer</td>
            <td>San Francisco</td>
            <td>28</td>
            <td>2011/06/07</td>
            <td>$206,850</td>
        </tr>
        <tr>
            <td>Fiona Green</td>
            <td>Chief Operating Officer (COO)</td>
            <td>San Francisco</td>
            <td>48</td>
            <td>2010/03/11</td>
            <td>$850,000</td>
        </tr>
        <tr>
            <td>Shou Itou</td>
            <td>Regional Marketing</td>
            <td>Tokyo</td>
            <td>20</td>
            <td>2011/08/14</td>
            <td>$163,000</td>
        </tr>
        <tr>
            <td>Michelle House</td>
            <td>Integration Specialist</td>
            <td>Sydney</td>
            <td>37</td>
            <td>2011/06/02</td>
            <td>$95,400</td>
        </tr>
        <tr>
            <td>Suki Burks</td>
            <td>Developer</td>
            <td>London</td>
            <td>53</td>
            <td>2009/10/22</td>
            <td>$114,500</td>
        </tr>
        <tr>
            <td>Prescott Bartlett</td>
            <td>Technical Author</td>
            <td>London</td>
            <td>27</td>
            <td>2011/05/07</td>
            <td>$145,000</td>
        </tr>
        <tr>
            <td>Gavin Cortez</td>
            <td>Team Leader</td>
            <td>San Francisco</td>
            <td>22</td>
            <td>2008/10/26</td>
            <td>$235,500</td>
        </tr>
        <tr>
            <td>Martena Mccray</td>
            <td>Post-Sales support</td>
            <td>Edinburgh</td>
            <td>46</td>
            <td>2011/03/09</td>
            <td>$324,050</td>
        </tr>
        <tr>
            <td>Unity Butler</td>
            <td>Marketing Designer</td>
            <td>San Francisco</td>
            <td>47</td>
            <td>2009/12/09</td>
            <td>$85,675</td>
        </tr>
        <tr>
            <td>Howard Hatfield</td>
            <td>Office Manager</td>
            <td>San Francisco</td>
            <td>51</td>
            <td>2008/12/16</td>
            <td>$164,500</td>
        </tr>
        <tr>
            <td>Hope Fuentes</td>
            <td>Secretary</td>
            <td>San Francisco</td>
            <td>41</td>
            <td>2010/02/12</td>
            <td>$109,850</td>
        </tr>
        <tr>
            <td>Vivian Harrell</td>
            <td>Financial Controller</td>
            <td>San Francisco</td>
            <td>62</td>
            <td>2009/02/14</td>
            <td>$452,500</td>
        </tr>
        <tr>
            <td>Timothy Mooney</td>
            <td>Office Manager</td>
            <td>London</td>
            <td>37</td>
            <td>2008/12/11</td>
            <td>$136,200</td>
        </tr>
        <tr>
            <td>Jackson Bradshaw</td>
            <td>Director</td>
            <td>New York</td>
            <td>65</td>
            <td>2008/09/26</td>
            <td>$645,750</td>
        </tr>
        <tr>
            <td>Olivia Liang</td>
            <td>Support Engineer</td>
            <td>Singapore</td>
            <td>64</td>
            <td>2011/02/03</td>
            <td>$234,500</td>
        </tr>
        <tr>
            <td>Bruno Nash</td>
            <td>Software Engineer</td>
            <td>London</td>
            <td>38</td>
            <td>2011/05/03</td>
            <td>$163,500</td>
        </tr>
        <tr>
            <td>Sakura Yamamoto</td>
            <td>Support Engineer</td>
            <td>Tokyo</td>
            <td>37</td>
            <td>2009/08/19</td>
            <td>$139,575</td>
        </tr>
        <tr>
            <td>Thor Walton</td>
            <td>Developer</td>
            <td>New York</td>
            <td>61</td>
            <td>2013/08/11</td>
            <td>$98,540</td>
        </tr>
        <tr>
            <td>Finn Camacho</td>
            <td>Support Engineer</td>
            <td>San Francisco</td>
            <td>47</td>
            <td>2009/07/07</td>
            <td>$87,500</td>
        </tr>
        <tr>
            <td>Serge Baldwin</td>
            <td>Data Coordinator</td>
            <td>Singapore</td>
            <td>64</td>
            <td>2012/04/09</td>
            <td>$138,575</td>
        </tr>
        <tr>
            <td>Zenaida Frank</td>
            <td>Software Engineer</td>
            <td>New York</td>
            <td>63</td>
            <td>2010/01/04</td>
            <td>$125,250</td>
        </tr>
        <tr>
            <td>Zorita Serrano</td>
            <td>Software Engineer</td>
            <td>San Francisco</td>
            <td>56</td>
            <td>2012/06/01</td>
            <td>$115,000</td>
        </tr>
        <tr>
            <td>Jennifer Acosta</td>
            <td>Junior Javascript Developer</td>
            <td>Edinburgh</td>
            <td>43</td>
            <td>2013/02/01</td>
            <td>$75,650</td>
        </tr>
        <tr>
            <td>Cara Stevens</td>
            <td>Sales Assistant</td>
            <td>New York</td>
            <td>46</td>
            <td>2011/12/06</td>
            <td>$145,600</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011/03/21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009/02/27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010/07/14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008/11/13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Michael Bruce</td>
            <td>Javascript Developer</td>
            <td>Singapore</td>
            <td>29</td>
            <td>2011/06/27</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Donna Snider</td>
            <td>Customer Support</td>
            <td>New York</td>
            <td>27</td>
            <td>2011/01/25</td>
            <td>$112,000</td>
        </tr>
    </tbody>
</table>



Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Home/Register.cshtml
@model shad_web_app.Models.Entity.User

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

<div class="container">

    @if (ViewBag.adw != null)
    {
    <div>
        @if (ViewBag.adw2 == "ok")
        {
            <h3 class="text-success">Hello <b>@ViewBag.adw,</b> Wellcome to the Site.</h3>
            <h4 class="text-success">Please Loging to the Site for go Further.</h4>
            <br />
        }
        else if (ViewBag.adw2 == "not")
        {
            <h3 class="text-warning">Something Wrong : @ViewBag.adw2.</h3>
        }
        else
        {
            <h3 class="text-warning">Something Wrong : @ViewBag.adw2.</h3>
        }
    </div>
    }


    <form action="@Url.Action("reg","Api")" method="post">
        <div id="unamediv" class="form-group">
            <label>Username</label>
            <input id="uname" class="form-control" type="text" placeholder="Enter Your Username" name="UserName" />
            <p id="uname_err" class="text-danger bg-danger"></p>
        </div>

        <div id="upassdiv" class="form-group">
            <label>Password</label>
            <input id="upass" class="form-control" type="password" placeholder="Enter Your Password" name="UserPassword" />
            <p id="upass_err" class="text-danger bg-danger"></p>
        </div>

        <div id="uagediv" class="form-group">
            <label>Age</label>
            <input id="uage" class="form-control" type="number" placeholder="Enter Your Age" name="UserAge" />
            <p id="uage_err" class="text-danger bg-danger"></p>
        </div>

        <div id="uaddressdiv" class="form-group">
            <label>Address</label>
            <input id="uaddress" class="form-control" type="text" placeholder="Enter Your Address" name="UserAddress" />
            <p id="uaddress_err" class="text-danger bg-danger"></p>
        </div>

        <div class="form-group">
            <input class="btn btn-primary" type="submit" />
        </div>
    </form>

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {

            $("#uname_err").hide();
            $("#upass_err").hide();
            $("#uage_err").hide();
            $("#uaddress_err").hide();
            ////
            $("#unamediv").focusout(function () {
                chechName();
            });

            $("#unamediv").focusin(function () {
                $("#uname_err").hide();
            });
            ////
            $("#upassdiv").focusout(function () {
                checkPass();
            });

            $("#upassdiv").focusin(function () {
                $("#upass_err").hide();
            });
            ////
            $("#uagediv").focusout(function () {
                checkAge();
            });

            $("#uagediv").focusin(function () {
                $("#uage_err").hide();
            });
            ////
            $("#uaddressdiv").focusout(function () {
                checkAddress();
            });

            $("#uaddressdiv").focusin(function () {
                $("#uaddress_err").hide();
            });

            function chechName() {
                var len = $("input[id=uname]").val().length;
                if (len == 0) {
                    $("#uname_err").text("Cannot Empty Username Field!");
                    $("#uname_err").show();
                }
                else if (/\d/.test($("input[id=uname]").val())) {
                    $("#uname_err").text("Cannot User Numbers in Username Field!");
                    $("#uname_err").show();
                }
            }

            function checkPass() {
                var len = $("input[id=upass]").val().length;
                if (len == 0) {
                    $("#upass_err").text("Cannot Empty Password Field!");
                    $("#upass_err").show();
                }
                else if (len < 2 || len > 10) {
                    $("#upass_err").text("Password Should be 2-10 characters!");
                    $("#upass_err").show();
                }
            }

            function checkAge() {
                var len = $("input[id=uage]").val().length;
                var age = parseInt($("input[id=uage]").val());
                if (len <= 0 || len >= 3) {
                    $("#uage_err").text("Enter Valid Age!");
                    $("#uage_err").show();
                }
                else if (age < 18 || age > 80) {
                    $("#uage_err").text("Age Should be above 18 years!");
                    $("#uage_err").show();
                }
            }

            function checkAddress() {
                var len = $("input[id=uaddress]").val().length;
                if (len == 0) {
                    $("#uaddress_err").text("Cannot Empty Address Field!");
                    $("#uaddress_err").show();
                }
            }
        });
    </script>

    <div>
        <a href="../Home/login_view">Login!</a>
    </div>
</div>

Views/Home/ResetPassword.cshtml

@{
    ViewBag.Title = "ResetPassword";
}

<h2>ResetPassword</h2>


Views/Home/login_view.cshtml
<div class="container">
    @{
        ViewBag.Title = "Login Page";
    }

    <h2>Please Login to the Site.</h2>

    @*@if (ViewBag.msg == "not" || ViewBag.mg == "error")
    {
        <h3 class="text-danger">Somethings Wrong</h3>
    }
    else
    {
        <h1>asdasdasdsad</h1>
    }*@

    <form action="@Url.Action("auth", "Api")" method="post">

        <div class="form-group">
            <label>Enter Username</label>
            <input class="form-control" type="text" placeholder="Enter Username" name="uname" />
        </div>

        <div class="form-group">
            <label>Enter Password</label>
            <input class="form-control" type="password" placeholder="Enter Password" name="upass" />
        </div>

        <div>
            <input class="btn btn-primary" type="submit" value="Login" />
        </div>

    </form>

    <br />
    <div">
        <p><a class="text-primary" href="../Home/reg_view">Register With Us! </a></p>
        <p><a class="text-primary" href="../Home/resetpw"> Forgot password?</a></p>
</div>
    
